#!/bin/bash
rm -rf ~/.vscode/extensions

code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.Bookmarks
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension annsk.alignment
code --install-extension apility.beautify-blade
code --install-extension christopherstyles.html-entities
code --install-extension codezombiech.gitignore
code --install-extension codingyu.laravel-goto-view
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cweijan.vscode-mysql-client2
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension GrapeCity.gc-excelviewer
code --install-extension IBM.output-colorizer
code --install-extension IHunte.laravel-blade-wrapper
code --install-extension johnpapa.vscode-peacock
code --install-extension kokororin.vscode-phpfmt
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension marabesi.php-import-checker
code --install-extension MehediDracula.php-constructor
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension neilbrayfield.php-docblocker
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension pomber.git-file-history
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.vscode-commons
code --install-extension rocketseat.theme-omni
code --install-extension ryannaddy.laravel-artisan
code --install-extension shufo.vscode-blade-formatter
code --install-extension stef-k.laravel-goto-controller
code --install-extension stevejpurves.cucumber
code --install-extension syler.sass-indented
code --install-extension TabNine.tabnine-vscode
code --install-extension wmaurer.change-case
code --install-extension xabikos.JavaScriptSnippets